name: 'HTML2PDF'
description: 'Convert an HTML file to a PDF document'
inputs:
  html:
    description: 'html file to convert'
    required: true
outputs:
  pdf:
    description: 'output file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -html ${{ inputs.html }}
    - -output ${{ inputs.html }}.pdf
